---
title: Jenny Shi
timezone: UTC
collections:
  category:
    title: Category
    output: true
    layout: category
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    layout: project
  uploads:
    title: Uploads
    output: false
  yeet:
    title: yeet
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: projects
  values:
    layout: project
description: painter and artist based in palo alto.
baseurl: 
url: https://www.jennyshi.me
markdown: kramdown
theme: minima
first_link: "Series 1"
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
