---
title: Jenny Shi
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    layout: project
  year:
    title: Year
    output: true
    layout: year
  uploads:
    title: Uploads
    output: false
  yeet:
    title: yeet
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: projects
  values:
    layout: project
description: painter and artist based in palo alto.
baseurl: 
url: https://www.jennyshi.me
contact-link: mailto:hello@jennyshi.me
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
