---
title: Jenny Shi
timezone: UTC
collections:
  category:
    title: Category
    output: true
    layout: category
  projects:
    title: Projects
    output: true
    layout: project
  uploads:
    title: Uploads
    output: false
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: projects
  values:
    layout: project
description: painter and artist based in palo alto.
baseurl: 
url: https://www.jennyshi.me
markdown: kramdown
theme: minima
first_link: Series 1
exclude:
- Gemfile
- Gemfile.lock
sass:
  style: compressed
tag_page_layout: category
tag_page_dir: cat_test