---
title: Jenny Shi
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    layout: project
  uploads:
    title: Uploads
    output: false
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: projects
  values:
    layout: project
email: 
description: painter and artist based in palo alto.
baseurl: 
url: https://www.jennyshi.me
link1-name: instagram
link1-url: https://instagram.com
link2-name: linkedin
link2-url: https://linkedin.com
link3-name: contact
link3-url: mailto:hello@jennyshi.me
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
