---
title: Jenny Shi
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    layout: project
  uploads:
    title: Uploads
    output: false
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: projects
  values:
    layout: project
email: 
description: painter and artist based in palo alto.
about: Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Etiam porta sem malesuada magna mollis euismod. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.
baseurl: 
url: https://www.jennyshi.me
contact-link: mailto:hello@jennyshi.me
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock