---
label: Project
hide_body: true
display_field: title
fields:
- type: text
  name: title
  label: Title
  description: Title of the thing
  config:
    required: true
- type: datetime
  name: date
  label: Date
  description: Date that you made the thing
- type: list
  name: categories
  label: Categories
  config:
    use_select: true
    source:
      type: simple
    options:
    - series 1
    - series 2
    - landscapes
    - portraits
    min: '1'
    max: '1'
- type: text
  name: description
  label: Description
  description: Description of the thing
- type: file
  name: image
  description: Now relying on only one image for both the category page and the project
    page. Should be fairly high res.
  label: Image
  config:
    maxSize: '10'
- name: medium
  type: text
  config:
    required: false
  label: Medium
  description: 'ex: "Oil on canvas"'
- name: style
  type: text
  config:
    required: false
  label: Style
  description: 'ex: "Cubism"'
pages:
- _projects/bleached-interstellar-dust.md
