---
label: Project
hide_body: true
display_field: title
fields:
- type: file
  name: image
  description: Now relying on only one image for both the category page and the project
    page. Should be fairly high res.
  label: Image
  config:
    maxSize: '10'
- type: list
  name: categories
  label: Categories
  config:
    use_select: true
    source:
      type: simple
    options:
    - series 1
    - series 2
    - landscapes
    - portraits
    min: '1'
    max: '1'
- type: text
  name: title
  label: Title
  description: Title of the thing
  config:
    required: true
- type: datetime
  name: date
  label: Date
  description: Date that you made the thing
- type: text
  name: description
  label: Description
  description: Description of the thing
- name: medium
  type: text
  config:
    required: false
  label: Medium
  description: 'ex: "Oil on canvas"'
- name: style
  type: text
  config:
    required: false
  label: Style
  description: 'ex: "Cubism"'
pages:
- _projects/headless-worms.md
- _projects/decay1.markdown
- _projects/decay2.markdown
- _projects/decay3.markdown
- _projects/phantoms.markdown
- _projects/deconstructed.markdown
- _projects/emily.markdown
- _projects/witches-hair.md
- _projects/bleached-interstellar-dust.md
- _projects/yeet3.markdown
- _projects/battle-of-the-waffle.markdown
- _projects/t-4-bacteriophages.md
- _projects/haystack.markdown
- _projects/yeet2.markdown
- _projects/yeet.markdown
- _projects/parasitic-cycle.markdown
- _projects/blueberries-and-antibodies.markdown
- _projects/the-things-we-cannot-touch.md
- _projects/self-portrait.md
- _projects/rhizobia.markdown
- _projects/hulu.markdown
- _projects/pandemonium.md
- _projects/dad.markdown
- _projects/raveling-mist.md
- _projects/warrior.md
- _projects/waltz-of-interstellar-volvox.markdown
- _projects/mom.md
- _projects/mom-2.markdown
- _projects/fleeting-moment.markdown
- _projects/drooling-chromosomes.markdown
- _projects/cotyledon-cross-section-427.md
- _projects/cell-to-paper.markdown
